{{- if .Values.apiExtension.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
    app.kubernetes.io/name: api-extension
    control-plane: controller-manager
  name: api-extension-controller-manager
  namespace: {{ .Release.Namespace }}
  {{- with .Values.apiExtension.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
