{{- if .Values.apiExtension.create -}}
{{- $registry := .Values.apiExtension.image.registry -}}
{{- $repository := default "harikube/api-extension" .Values.apiExtension.image.repository -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
    app.kubernetes.io/name: api-extension
    control-plane: controller-manager
  name: api-extension-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.apiExtension.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api-extension
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.apiExtension.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "harikube.labels" . | nindent 8 }}
        app.kubernetes.io/name: api-extension
        control-plane: controller-manager
        {{- with .Values.apiExtension.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: api-extension-controller-manager
      {{- with .Values.apiExtension.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiExtension.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiExtension.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.apiExtension.podSecurityContext | nindent 8 }}
      containers:
      - args:
          {{- toYaml .Values.apiExtension.args | nindent 10 }}
        command:
        - /manager
        env:
        - name: CORE_RESOURCES
          valueFrom:
            configMapKeyRef:
              key: resources
              name: api-extension-core-resources
        - name: HARIKUBE_URLS
          valueFrom:
            secretKeyRef:
              name: api-extension-harikube-connection
              key: harikube-urls
        - name: DECISION_MAKER_URL
          valueFrom:
            configMapKeyRef:
              name: api-extension-decision-maker
              key: url
        - name: DECISION_MAKER_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: api-extension-decision-maker
              key: timeout
        image: "{{- if $registry -}}{{ $registry }}/{{- end -}}{{ $repository }}:{{ .Values.apiExtension.image.tag }}"
        imagePullPolicy: {{ .Values.apiExtension.image.pullPolicy }}
        livenessProbe:
          {{- toYaml .Values.apiExtension.livenessProbe | nindent 10 }}
        name: manager
        ports:
        - containerPort: {{ .Values.apiExtension.service.api.targetPort }}
          name: apiserver
          protocol: TCP
        readinessProbe:
          {{- toYaml .Values.apiExtension.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.apiExtension.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.apiExtension.securityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/k8s-apiserver-server/serving-certs
          name: apiserver-certs
          readOnly: true
        - mountPath: /tmp/harikube-middleware-crt
          name: harikube-middleware-crt
          readOnly: true
      - name: decision-maker
        image: node:18-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: DECISION_MAKER_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: api-extension-decision-maker
              key: provider
        - name: DECISION_MAKER_PORT
          valueFrom:
            configMapKeyRef:
              name: api-extension-decision-maker
              key: port
        - name: LAYA_CACHE
          valueFrom:
            configMapKeyRef:
              name: api-extension-decision-maker
              key: laya-cache
        - name: DECISION_MAKER_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: api-extension-decision-maker
              key: timeout
        command:
        - node
        - /opt/decision-maker/server.mjs
        volumeMounts:
        - name: decision-maker-script
          mountPath: /opt/decision-maker/server.mjs
          subPath: server.mjs
          readOnly: true
        {{- with .Values.apiExtension.volumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: apiserver-certs
        secret:
          secretName: v1-api-extension-crt
      - name: harikube-middleware-crt
        secret:
          secretName: harikube-middleware-crt
      - name: decision-maker-script
        configMap:
          name: api-extension-decision-maker
      {{- with .Values.apiExtension.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
