{{- if .Values.controllerManager.create -}}
{{- if .Values.certManagerIntegration.create -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-controller-manager-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-controller-manager-crt
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - localhost
  - harikube-controller-manager-svc
  - harikube-controller-manager-svc.{{ .Release.Namespace }}
  - harikube-controller-manager-svc.{{ .Release.Namespace }}.svc
  - harikube-controller-manager-svc.{{ .Release.Namespace }}.cluster.local
  - harikube-controller-manager-svc.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: harikube-controller-manager-issuer
  secretName: harikube-controller-manager-crt
{{- else -}}
{{- $tls := include "harikube.getOrGenTls" (dict "root" . "secretName" "harikube-controller-manager-crt" "cn" "harikube-controller-manager-svc") | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: harikube-controller-manager-crt
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $tls.caCert }}
  tls.crt: {{ $tls.tlsCert }}
  tls.key: {{ $tls.tlsKey }}
{{- end }}
{{- end }}
