apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-middleware-pvc
spec:
  {{- toYaml .Values.middleware.pvc | nindent 2 }}