{{- if .Values.middleware.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: my-app
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: lease-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: lease-manager
  namespace: LEASE_NAMESPACE
subjects:
  - kind: ServiceAccount
    name: my-app
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lease-manager
{{- end }}
