{{- if .Values.middleware.create -}}
{{- if .Values.certManagerIntegration.create -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-middleware-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-middleware-crt
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - localhost
  - harikube-middleware-svc
  - harikube-middleware-svc.{{ .Release.Namespace }}
  - harikube-middleware-svc.{{ .Release.Namespace }}.svc
  - harikube-middleware-svc.{{ .Release.Namespace }}.cluster.local
  - harikube-middleware-svc.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: harikube-middleware-issuer
  secretName: harikube-middleware-crt
{{- else -}}
{{- $tls := include "harikube.getOrGenTls" (dict "root" . "secretName" "harikube-middleware-crt" "cn" "harikube-middleware-svc") | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: harikube-middleware-crt
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $tls.caCert }}
  tls.crt: {{ $tls.tlsCert }}
  tls.key: {{ $tls.tlsKey }}
{{- end }}
{{- end }}
