{{- if .Values.serverlessKubeWatchTrigger.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
    app.kubernetes.io/name: serverless-kube-watch-trigger
    control-plane: controller-manager
  name: serverless-kube-watch-trigger-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.serverlessKubeWatchTrigger.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: serverless-kube-watch-trigger
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      {{- with .Values.serverlessKubeWatchTrigger.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "harikube.labels" . | nindent 8 }}
        app.kubernetes.io/name: serverless-kube-watch-trigger
        control-plane: controller-manager
        {{- with .Values.serverlessKubeWatchTrigger.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ include "harikube.serverlessKubeWatchTrigger.serviceAccountName" . }}
      {{- with .Values.serverlessKubeWatchTrigger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serverlessKubeWatchTrigger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serverlessKubeWatchTrigger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.serverlessKubeWatchTrigger.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        image: "{{ if .Values.serverlessKubeWatchTrigger.image.registry }}{{ .Values.serverlessKubeWatchTrigger.image.registry }}/{{ end }}{{ default "harikube/serverless-kube-watch-trigger" .Values.serverlessKubeWatchTrigger.image.repository }}:{{ .Values.serverlessKubeWatchTrigger.image.tag }}"
        imagePullPolicy: {{ .Values.serverlessKubeWatchTrigger.image.pullPolicy }}
        command:
        - "/manager"
        {{- $args := list }}
        {{- with .Values.serverlessKubeWatchTrigger.args }}
        {{- range . }}
          {{- if not (or (hasPrefix . "--leader-elect") (eq . "--leader-elect")) }}
            {{- $args = append $args . }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.serverlessKubeWatchTrigger.leaderElection.enabled }}
          {{- $args = append $args "--leader-elect" }}
        {{- else }}
          {{- $args = append $args "--leader-elect=false" }}
        {{- end }}
        args:
{{- toYaml $args | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.serverlessKubeWatchTrigger.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.serverlessKubeWatchTrigger.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.serverlessKubeWatchTrigger.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.serverlessKubeWatchTrigger.securityContext | nindent 10 }}
      volumes:
      {{- with .Values.serverlessKubeWatchTrigger.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
