controlPlane:
  distro:
    k8s:
      enabled: true
      image:
        registry: quay.io
        repository: harikube/kubernetes
        tag: v1.35.3
      imagePullPolicy: IfNotPresent
      apiServer:
        enabled: true
        extraArgs:
        - --feature-gates=WatchList=true,WatchListClient=true,VolumeAttributesClass=true,MutatingAdmissionPolicy=true
        - --watch-cache=false
        - --etcd-servers=https://harikube-middleware-svc.harikube:2379
        - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
        - --etcd-certfile=/etc/kubernetes/pki/etcd/tls.crt
        - --etcd-keyfile=/etc/kubernetes/pki/etcd/tls.key
        - --runtime-config=admissionregistration.k8s.io/v1beta1=true
        - --storage-media-type=application/json
        - --max-requests-inflight=900
        - --max-mutating-requests-inflight=300
      controllerManager:
        enabled: true
      scheduler:
        enabled: true
  coredns:
    enabled: true
  backingStore:
    etcd:
      deploy:
        enabled: false
    database:
      embedded:
        enabled: false
  statefulSet:
    highAvailability:
      replicas: 1
    persistence:
      addVolumes:
      - name: etcd-certs
        secret:
          secretName: harikube-middleware-crt
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      addVolumeMounts:
        - name: etcd-certs
          mountPath: /etc/kubernetes/pki/etcd
          readOnly: true
sync:
  toHost:
    pods:
      enabled: true
    secrets:
      enabled: true
    configMaps:
      enabled: true
    services:
      enabled: true
    endpoints:
      enabled: true
    ingresses:
      enabled: true
    networkPolicies:
      enabled: true
    persistentVolumes:
      enabled: true
    persistentVolumeClaims:
      enabled: true
    storageClasses:
      enabled: true
    serviceAccounts:
      enabled: true
    podDisruptionBudgets:
      enabled: true
    priorityClasses:
      enabled: true
  fromHost:
    nodes:
      enabled: true
    secrets:
      enabled: true
      mappings:
        byName:
          "harikube/topology-config": "harikube/topology-config"
networking:
  replicateServices:
    fromHost:
      - from: harikube/harikube-middleware-svc
        to: harikube/harikube-middleware-svc