name: Release

on:
  push:
    branches:
    - release-v**
    - rc-v**
    - beta-v**
    - alpha-v**
    - dev-v**

concurrency: 
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract version
        run: echo "version=$(cat harikube/Chart.yaml | grep '^version' | cut -d' ' -f2)" >> $GITHUB_OUTPUT
        id: extract_version

      - name: Helm build chart
        run: devbox run helm package ./harikube

      - name: Helm login
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | devbox run helm registry login ${{ vars.REGISTRY }} \
            --username "${{ vars.REGISTRY_USER }}" \
            --password-stdin

      - name: Helm push chart
        run: |
          devbox run helm push harikube-${{ steps.extract_version.outputs.version }}.tgz oci://${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}

      - name: Create release
        if: ${{ !startsWith(github.ref, 'refs/heads/dev-') }}
        uses: mhmxs/milestone-release-action@main
        with:
          milestone-title: ${{ steps.extract_branch.outputs.branch }}
          pre-body: |
            ## Installation

            ### Prerequisets

            - Kubernetes cluster; supported versions Vanilla, EKS, AKS, GKE, RKE2, OpenShift >=1.34.0
            - Prometheus if any of the monitoring.create is true 

            ### Helm Deploy

            ```bash
            helm install harikube oci://quay.io/harikube/harikube \
              --version ${{ steps.extract_version.outputs.version }} \
              --create-namespace \
              --namespace harikube \
              --set vcluster.exportKubeConfig.server=https://harikube.harikube:443
            kubectl wait -n harikube --for=jsonpath='{.status.readyReplicas}'=1 statefulset/harikube --timeout=5m
            ```

            > If you change namespace, please `--set vcluster.exportKubeConfig.server=https://harikube.<NAMESPACE>:443`

            You can integrate services with cert-manager.

            ```bash
            --set certManagerIntegration.create=true
            ```
            
            You can enable network policies. You have to create namespace manually, label the namespace and skip `--create-namespace` flag.

            ```bash
            --set middleware.networkPolicy.create=true # kubectl label namespace harikube harikube.info/<NAMESPACE>-middleware=enabled --overwrite
            ```

            You can enable ServiceMonitors for middleware.

            ```bash
            --set middleware.monitoring.create=true
            ```

            You can enable the MutatingAdmissionPolicy to label non core resources with skip-controller-manager-metadata-caching.

            ```bash
            --set mutatingAdmissionPolicy.create=true
            ```

            You can enable a scalable contorl plane extension.

            ```bash
            --set apiServer.create=true
            --set controllerManager.create=true # By default all controllers are disabled, enable controllers you want to run.
            ```

            You can enable network policies for control plane.

            ```bash
            --set apiServer.networkPolicy.create=true # kubectl label namespace harikube harikube.info/<NAMESPACE>-apiserver=enabled --overwrite
            --set controllerManager.networkPolicy.create=true # kubectl label namespace harikube harikube.info/<NAMESPACE>-controllermanager=enabled --overwrite
            ```

            You can enable ServiceMonitors per service.

            ```bash
            --set apiServer.monitoring.create=true
            --set controllerManager.monitoring.create=true
            ```

            #### Enterprise Editioin

            Set `enterprise.key`, `enterprise.user` and `enterprise.password`, then set `operator.create=true` and the chart will deploy licensed edition to the target cluster.

            ## vCluster connection

            Connect via vCluster CLI.

            ```bash
            vcluster connect harikube
            ```

            Connect via vCluster KUBECONFIG.

            ```bash
            kubectl get secret -n harikube vc-harikube -o yaml
            ```

            > 🔓 vCluster simplifies the operational workflow by automatically updating your local environment. For more details how to disable this behaviour, or how to get config by service account for example please wisit the official docs` [Access and expose vCluster](https://www.vcluster.com/docs/vcluster/manage/accessing-vcluster) section.

            > 🔓 For service access from host, the vCluster setup keeps things simple: Create your ServiceAccount, create a secret annotated with `kubernetes.io/service-account.name` (example below), and vCluster will sync the secret to the host cluster.

            ```yaml
            apiVersion: v1
            kind: Secret
            metadata:
              name: remote-your-service-account-name
              annotations:
                kubernetes.io/service-account.name: "your-service-account-name"
            type: kubernetes.io/service-account-token
            ```

            On the host cluster, you can fetch the connection details.

            ```bash
            KUBE_API_URL=harikube.harikube.svc.cluster.local
            TOKEN=$(kubectl get secret -n harikube remote-your-service-account-name-x-default-x-harikube -o jsonpath='{.data.token}' | base64 -d)
            CA_CERT=$(kubectl get secret -n harikube remote-your-service-account-name-x-default-x-harikube -o jsonpath='{.data.ca\.crt}' | base64 -d)
            ```

            ## Customization

            The manifests gereted for the release are covering basic setup. You can customize your setup, by changing `vcluster` values.

            ## Important Requirement

            To use these features to their full potential, you cannot use "standard" Kubernetes. You must use the patched images provided by us These patches allow the Kubernetes API to understand the special storage instructions Kine is waiting for.

            - [Kubernetes Patches](https://github.com/HariKube/kubernetes-patches)
            - [Patched Images](https://quay.io/repository/harikube/kubernetes?tab=tags&tag=latest)


            ## Release Notes
          draft: true
          prerelease: ${{ startsWith(github.ref, 'refs/heads/rc-') || startsWith(github.ref, 'refs/heads/beta-') || startsWith(github.ref, 'refs/heads/alpha-') }}
          files: harikube-${{ steps.extract_version.outputs.version }}.tgz
