name: Release

on:
  push:
    branches:
    - release-v**
    - rc-v**
    - beta-v**
    - alpha-v**
    - dev-v**

concurrency: 
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract version
        run: echo "version=$(cat harikube/Chart.yaml | grep '^version' | cut -d' ' -f2)" >> $GITHUB_OUTPUT
        id: extract_version

      - name: Helm build chart
        run: devbox run helm package ./harikube

      - name: Helm login
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | devbox run helm registry login ${{ vars.REGISTRY }} \
            --username "${{ vars.REGISTRY_USER }}" \
            --password-stdin

      - name: Helm push chart
        run: |
          devbox run helm push harikube-helm-charts-${{ steps.extract_version.outputs.version }}.tgz oci://${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}

      - name: Create release
        if: ${{ !startsWith(github.ref, 'refs/heads/dev-') }}
        uses: mhmxs/milestone-release-action@main
        with:
          milestone-title: ${{ steps.extract_branch.outputs.branch }}
          pre-body: |
            # harikube-helm-charts

            ## Installation
            
            ```bash
            kubectl create namespace harikube
            kubectl create secret generic -n harikube harikube-license --from-file=LICENSE_FILE
            kubectl create secret docker-registry harikube-registry-secret \
              --docker-server=registry.harikube.info \
              --docker-username=REGISTRY_USER \
              --docker-password="REGISTRY_PASSWORD" \
              --namespace=harikube
          
            helm install harikube oci://${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/harikube-helm-charts \
              --version ${{ steps.extract_version.outputs.version }} \
              --debug \
              --namespace harikube
            kubectl wait -n harikube --for=jsonpath='{.status.readyReplicas}'=1 deployment/harikube-operator-deploy --timeout=2m
            kubectl wait -n harikube --for=jsonpath='{.status.readyReplicas}'=1 deployment/harikube-middleware-deploy --timeout=2m
            ```

            You can enable network policies, in this case you have to label the namespace before you install HariKube.

            ```bash
            kubectl label namespace harikube harikube.info/harikube-middleware=enabled --overwrite # --set middleware.networkPolicy.create=true
            kubectl label namespace harikube harikube.info/harikube-vcluster=enabled --overwrite # --set vcluster.networkPolicy.create=true
            ```

            You can enable ServiceMonitors per service.

            ```bash
            --set middleware.monitoring.create=true
            --set operator.monitoring.create=true
            ```

            You can enable the MutatingAdmissionPolicy to label non core resources with skip-controller-manager-metadata-caching.

            ```bash
            --set mutatingAdmissionPolicy.create=true
            ```

            ### Install vCluster API only
            
            ```bash
            helm install harikube-vcluster https://charts.loft.sh/charts/vcluster-0.32.1.tgz \
              --debug \
              --namespace harikube \
              --values harikube/vcluster/api-config.yaml
            kubectl wait -n harikube --for=jsonpath='{.status.readyReplicas}'=1 statefulset/harikube-vcluster --timeout=5m
            ```

            ### Install vCluster workload support
            
            ```bash
            helm install harikube-vcluster https://charts.loft.sh/charts/vcluster-0.32.1.tgz \
              --debug \
              --namespace harikube \
              --values harikube/vcluster/workload-config.yaml
            kubectl wait -n harikube --for=jsonpath='{.status.readyReplicas}'=1 statefulset/harikube-vcluster --timeout=5m
            ```
            
            ### Install scalable control pvclaimbinde

            ```bash
            helm install harikube-control-plane ./harikube \
              --debug \
              --namespace $(NAMESPACE) \
              --set namespace.create=false \
              --set middleware.create=false \
              --set operator.create=false \
              --set apiServer.create=true \
              --set controllerManager.create=true
            ```

            You can enable network policies.

            ```bash
            kubectl label namespace harikube harikube.info/harikube-apiserver=enabled --overwrite # --set apiServer.networkPolicy.create=true
            kubectl label namespace harikube harikube.info/harikube-controllermanager=enabled --overwrite # --set controllerManager.networkPolicy.create=true
            ```

            You can enable ServiceMonitors per service.

            ```bash
            --set apiServer.monitoring.create=true
            --set controllerManager.monitoring.create=true
            ```

            ## Release Notes
          draft: true
          prerelease: ${{ startsWith(github.ref, 'refs/heads/rc-') || startsWith(github.ref, 'refs/heads/beta-') || startsWith(github.ref, 'refs/heads/alpha-') }}
          files: harikube-helm-charts-${{ steps.extract_version.outputs.version }}.tgz
